#!/usr/bin/env python3
"""
（知識庫維護）由 brain/<skill>/skill.md 自動產生 .claude/skills/<skill>/SKILL.md 入口

brain/ 是唯一的內容來源；.claude/skills/ 只放 Claude Code 用來「依使用者的話自動觸發」
的薄入口（name + description + 一句「去讀 brain/<skill>/skill.md」）。不要手改入口檔，
改 brain/<skill>/skill.md 的 frontmatter 後重跑本腳本。不在 brain/ 的舊入口會被移除。

用法：python sync_claude_skills.py [--check]   # --check：只檢查是否同步，不寫檔（結束碼 1 = 不同步）
"""
import argparse
import json
import shutil

from _kb import BRAIN, frontmatter, run, skills

CLAUDE_SKILLS = BRAIN.parent / ".claude" / "skills"
MARK = "<!-- generated by brain/_tools/sync_claude_skills.py — do not edit -->"


def render(name, fm):
    return (f"---\nname: {name}\ndescription: {json.dumps(fm.get('description', ''), ensure_ascii=False)}\n---\n{MARK}\n\n"
            f"Read `brain/{name}/skill.md` first and follow it. All rules, procedures and scripts for this "
            f"Skill live under `brain/{name}/`; shared conventions are in `brain/_core/`.\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    wanted = {}
    for s in skills():
        fm = frontmatter((BRAIN / s / "skill.md").read_text(encoding="utf-8"))
        wanted[s] = render(s, fm)

    stale = []
    for name, content in wanted.items():
        f = CLAUDE_SKILLS / name / "SKILL.md"
        if not f.is_file() or f.read_text(encoding="utf-8") != content:
            stale.append(name)
            if not args.check:
                f.parent.mkdir(parents=True, exist_ok=True)
                f.write_text(content, encoding="utf-8")
    extra = [p.name for p in CLAUDE_SKILLS.iterdir() if p.is_dir() and p.name not in wanted] \
        if CLAUDE_SKILLS.exists() else []
    if not args.check:
        for name in extra:
            shutil.rmtree(CLAUDE_SKILLS / name)
    print(f"skills: {list(wanted)}; updated: {stale}; removed: {extra}" if not args.check
          else f"out of sync: {stale + extra}" if stale or extra else "in sync")
    return 1 if args.check and (stale or extra) else 0


if __name__ == "__main__":
    run(main)
