"""
Writes a generated report back to Lark (table / doc / message).
"""


def push(report):
    """
    Push a generated report to Lark.

    Args:
        report: A report generated by reports.daily_report.generate() or
            reports.weekly_report.generate().
    """
    raise NotImplementedError("lark_writer.push() is not implemented yet.")
