#!/usr/bin/env python3
"""
（知識庫維護）由 brain/skill.md（母入口）自動產生 .claude/skills/opbrain/SKILL.md

brain/ 是唯一的內容來源；.claude/skills/ 只註冊**一個**入口，讓 Claude Code 一律從
brain/skill.md 進來，依序走 ① 找領域 → ② 讀 brain/<領域>/domain.md → ③ 讀子 Skill 的 skill.md。
子 Skill 不再各自註冊，否則 Claude 會直接跳進子 Skill，略過 ①②。
不要手改入口檔，改 brain/skill.md 的 frontmatter 後重跑本腳本。其他舊入口會被移除。

同時檢查分流是否走得通（任一項不符就失敗）：
  E-1 brain/skill.md 存在，frontmatter 有 name、description
  E-2 brain/skill.md 列出的每個 brain/<領域>/domain.md 都存在
  E-3 每個 Skill（brain/<領域>/<skill>/skill.md）都被至少一個 domain.md 收錄，否則從入口走不到
  E-4 domain.md 引用的每個 brain/<領域>/<skill>/skill.md 都存在（可跨領域引用）
  E-5 放有 Skill 的領域資料夾都有 domain.md，且被 brain/skill.md 列出

用法：python sync_claude_skills.py [--check]   # --check：只檢查，不寫檔（結束碼 1 = 不同步或分流不通）
"""
import argparse
import json
import re
import shutil

from _kb import BRAIN, frontmatter, run, skill_root, skills

CLAUDE_SKILLS = BRAIN.parent / ".claude" / "skills"
ENTRY = BRAIN / "skill.md"
MARK = "<!-- generated by brain/_framework/tools/sync_claude_skills.py — do not edit -->"
DOMAIN_RE = re.compile(r"brain/([a-z][a-z0-9\-]*)/domain\.md")
SKILL_RE = re.compile(r"brain/([a-z][a-z0-9\-]*/[a-z][a-z0-9\-]*)/skill\.md")   # brain/<領域>/<skill>/skill.md


def render(name, fm):
    return (f"---\nname: {name}\ndescription: {json.dumps(fm.get('description', ''), ensure_ascii=False)}\n---\n{MARK}\n\n"
            "Read `brain/skill.md` first and follow it: ① pick the domain there, ② read that domain's "
            "`brain/<domain>/domain.md` to pick the sub-Skills, ③ read each sub-Skill's `skill.md` for the exact "
            "command. Do not jump straight to a sub-Skill's `skill.md` without going through ① and ②. "
            "Shared conventions: `brain/_org/conventions.md`.\n")


def check_routing():
    """回傳 (入口 frontmatter, 錯誤清單)。"""
    if not ENTRY.is_file():
        return {}, ["E-1 missing brain/skill.md"]
    text = ENTRY.read_text(encoding="utf-8")
    fm = frontmatter(text)
    errors = [f"E-1 brain/skill.md frontmatter missing '{k}'" for k in ("name", "description") if not fm.get(k)]
    reachable = set()
    listed = set(DOMAIN_RE.findall(text))
    for domain in sorted(listed):
        f = BRAIN / domain / "domain.md"
        if not f.is_file():
            errors.append(f"E-2 brain/skill.md lists brain/{domain}/domain.md, which does not exist")
            continue
        for rel in sorted(set(SKILL_RE.findall(f.read_text(encoding="utf-8")))):
            if (BRAIN / rel / "skill.md").is_file():
                reachable.add(rel)
            else:
                errors.append(f"E-4 brain/{domain}/domain.md references brain/{rel}/skill.md, which does not exist")
    for s in skills():
        rel = skill_root(s).relative_to(BRAIN).as_posix()
        if rel not in reachable:
            errors.append(f"E-3 Skill '{s}' (brain/{rel}/) is not listed in any brain/<domain>/domain.md (unreachable from brain/skill.md)")
        domain = rel.split("/")[0]
        if domain not in listed or not (BRAIN / domain / "domain.md").is_file():
            errors.append(f"E-5 Skill '{s}' lives in brain/{domain}/, which has no domain.md listed in brain/skill.md")
    return fm, errors


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    fm, errors = check_routing()
    for e in errors:
        print(f"ERROR {e}")
    if errors:
        return 1

    name = fm["name"]
    wanted = {name: render(name, fm)}
    stale = []
    for n, content in wanted.items():
        f = CLAUDE_SKILLS / n / "SKILL.md"
        if not f.is_file() or f.read_text(encoding="utf-8") != content:
            stale.append(n)
            if not args.check:
                f.parent.mkdir(parents=True, exist_ok=True)
                f.write_text(content, encoding="utf-8")
    extra = [p.name for p in CLAUDE_SKILLS.iterdir() if p.is_dir() and p.name not in wanted] \
        if CLAUDE_SKILLS.exists() else []
    if not args.check:
        for n in extra:
            shutil.rmtree(CLAUDE_SKILLS / n)
    print(f"entry: {name}; updated: {stale}; removed: {extra}" if not args.check
          else f"out of sync: {stale + extra}" if stale or extra else "in sync")
    return 1 if args.check and (stale or extra) else 0


if __name__ == "__main__":
    run(main)
